INSERT INTO Dashboard.Widgets
(id, id_type_widget, source_php_widget, min_row, max_row, min_col, max_col, widgetType, unique_metric, numeric_rangeOption, number_metrics_widget, color_widgetOption, dimMap, widgetCategory, isNodeRedSender, domainType, defaultParameters, hasTimer, hasChartColor, hasDataLabels, hasChartLabels, hasTimeRange, hasCartesianPlane, hasChangeMetric, hasAddMode, isCollapsible)
VALUES(null, 'widgetSnap4D3', 'widgetSnap4D3.php', 1, 50, 1, 50, 'Percentuale', '', 1, 1, 1, NULL, 'dataViewer', 'no', NULL, '{
	"actuatorAttribute" : null,
	"actuatorEntity" : null,
	"actuatorTarget" : null,
	"attributeName" : null,
	"cancelDate" : null,
	"canceller" : null,
	"chartColor" : "#ffcc00",
	"chartLabelsFontColor" : null,
	"chartLabelsFontSize" : null,
	"color_w" : "#FFFFFF",
	"controlsPosition" : null,
	"controlsVisibility" : null,
	"dataLabelsFontColor" : null,
	"dataLabelsFontSize" : null,
	"defaultTab" : null,
	"enableFullscreenModal" : "no",
	"enableFullscreenTab" : "no",
	"entityJson" : null,
	"fontColor" : "#000000",
	"fontFamily" : "Auto",
	"fontSize" : 36,
	"frame_color_w" : "rgb(51, 204, 255)",
	"frequency_w" : 600,
	"headerFontColor" : "#FFFFFF",
	"hospitalList" : null,
	"infoJson" : null,
	"infoMessage_w" : null,
	"lastEditDate" : null,
	"lastSeries" : null,
	"link_w" : "none",
	"municipality_w" : null,
	"notificatorEnabled" : "no",
	"notificatorRegistered" : "no",
	"oldParameters" : null,
	"parameters" : null,
	"scaleX" : null,
	"scaleY" : null,
	"serviceUri" : null,
	"showTitle" : "yes",
	"size_columns" : 6,
	"size_rows" : 3,
	"styleParameters" : null,
	"temporal_range_w" : null,
	"udm" : "",
	"udmPos" : "below",
	"viewMode" : null,
	"zoomControlsColor" : null,
	"zoomFactor" : null
}', 'yes', 'yes', 'no', 'no', 'no', 'no', 'no', 'no', 'no');

---

INSERT INTO Dashboard.WidgetsIconsMap
(id, mainWidget, targetWidget, snap4CityType, icon, mono_multi, description, available, sm_based, defaultParametersMainWidget, defaultParametersTargetWidget, hasMainWidgetFactory, hasTargetWidgetFactory, comboName, widgetCategory)
VALUES(null, 'widgetSnap4D3', '', 'percentage', 'bar-content-horizontal.png', 'Mono', ' D3 chart viewer', 'true', 'no', '{
	"actuatorAttribute" : null,
	"actuatorEntity" : null,
	"actuatorTarget" : null,
	"attributeName" : null,
	"cancelDate" : null,
	"canceller" : null,
	"chartColor" : "#ffcc00",
	"chartLabelsFontColor" : null,
	"chartLabelsFontSize" : null,
	"color_w" : "#FFFFFF",
	"controlsPosition" : null,
	"controlsVisibility" : null,
	"dataLabelsFontColor" : null,
	"dataLabelsFontSize" : null,
	"defaultTab" : null,
	"enableFullscreenModal" : "no",
	"enableFullscreenTab" : "no",
	"entityJson" : null,
	"fontColor" : "#000000",
	"fontFamily" : "Auto",
	"fontSize" : 36,
	"frame_color_w" : "rgb(51, 204, 255)",
	"frequency_w" : 600,
	"headerFontColor" : "#FFFFFF",
	"hospitalList" : null,
	"infoJson" : null,
	"infoMessage_w" : null,
	"lastEditDate" : null,
	"lastSeries" : null,
	"link_w" : "none",
	"municipality_w" : null,
	"notificatorEnabled" : "no",
	"notificatorRegistered" : "no",
	"oldParameters" : null,
	"parameters" : null,
	"scaleX" : null,
	"scaleY" : null,
	"serviceUri" : null,
	"showTitle" : "yes",
	"size_columns" : 6,
	"size_rows" : 3,
	"styleParameters" : null,
	"temporal_range_w" : null,
	"udm" : "",
	"udmPos" : "below",
	"viewMode" : null,
	"zoomControlsColor" : null,
	"zoomFactor" : null
}', NULL, 'no', '["no"]', NULL, 'dataViewer');
