var trafficEventTypes = {
           type1 : {
              desc: "Accident",
              icon: "crash.png",
              mapIconLow: "crashMapLow.png",
              mapIconMed: "crashMapMed.png",
              mapIconHigh: "crashMapHigh.png"
           },
           type2 : {
              desc: "Activities",
              icon: "activity.png",
              mapIconLow: "genericMapLow.png",
              mapIconMed: "genericMapMed.png",
              mapIconHigh: "genericMapHigh.png"
           },
           type3 : {
              desc: "Action plan",
              icon: "actionPlan.png",
              mapIconLow: "genericMapLow.png",
              mapIconMed: "genericMapMed.png",
              mapIconHigh: "genericMapHigh.png"
           },
           type4 : {
              desc: "Average speed",
              icon: "averageSpeed.png",
              mapIconLow: "genericMapLow.png",
              mapIconMed: "genericMapMed.png",
              mapIconHigh: "genericMapHigh.png"
           },
           type5 : {
              desc: "Concentration",
              icon: "concentration.png",
              mapIconLow: "genericMapLow.png",
              mapIconMed: "genericMapMed.png",
              mapIconHigh: "genericMapHigh.png"
           },
           type6 : {
              desc: "Delays/Cancellations",
              icon: "delayCancellation.png",
              mapIconLow: "genericMapLow.png",
              mapIconMed: "genericMapMed.png",
              mapIconHigh: "genericMapHigh.png"
           },
           type7 : {
              desc: "Traffic equipment status",
              icon: "trafficEquipmentStatus.png",
              mapIconLow: "genericMapLow.png",
              mapIconMed: "genericMapMed.png",
              mapIconHigh: "genericMapHigh.png"
           },
           type8 : {
              desc: "Exhaust pollution",
              icon: "exhaustPollution.png",
              mapIconLow: "genericMapLow.png",
              mapIconMed: "genericMapMed.png",
              mapIconHigh: "genericMapHigh.png"
           },
           type9 : {
              desc: "Ferries/Trains",
              icon: "ferryTrain.png",
              mapIconLow: "genericMapLow.png",
              mapIconMed: "genericMapMed.png",
              mapIconHigh: "genericMapHigh.png"
           },
           type10 : {
              desc: "Flow",
              icon: "flow.png",
              mapIconLow: "genericMapLow.png",
              mapIconMed: "genericMapMed.png",
              mapIconHigh: "genericMapHigh.png"
           },
           type11 : {
              desc: "Fog/smoke/dust",
              icon: "fog.png",
              mapIconLow: "genericMapLow.png",
              mapIconMed: "genericMapMed.png",
              mapIconHigh: "genericMapHigh.png"
           },
           type12 : {
              desc: "Incident",
              icon: "crash.png",
              mapIconLow: "crashMapLow.png",
              mapIconMed: "crashMapMed.png",
              mapIconHigh: "crashMapHigh.png"
           },
           type13 : {
              desc: "Service information",
              icon: "info.png",
              mapIconLow: "genericMapLow.png",
              mapIconMed: "genericMapMed.png",
              mapIconHigh: "genericMapHigh.png"
           },
           type14 : {
              desc: "Individual vehicle data",
              icon: "vehicleData.png",
              mapIconLow: "genericMapLow.png",
              mapIconMed: "genericMapMed.png",
              mapIconHigh: "genericMapHigh.png"
           },
           type15 : {
              desc: "Level of service",
              icon: "serviceLevel.png",
              mapIconLow: "genericMapLow.png",
              mapIconMed: "genericMapMed.png",
              mapIconHigh: "genericMapHigh.png"
           },
           type16 : {
              desc: "Moving hazards",
              icon: "hazard.png",
              mapIconLow: "genericMapLow.png",
              mapIconMed: "genericMapMed.png",
              mapIconHigh: "genericMapHigh.png"
           },
           type17 : {
              desc: "Occupancy",
              icon: "questionMark.png",
              mapIconLow: "genericMapLow.png",
              mapIconMed: "genericMapMed.png",
              mapIconHigh: "genericMapHigh.png"
           },
           type18 : {
              desc: "Origin-destination matrix",
              icon: "matrix.png",
              mapIconLow: "genericMapLow.png",
              mapIconMed: "genericMapMed.png",
              mapIconHigh: "genericMapHigh.png"
           },
           type19 : {
              desc: "Obstruction hazards",
              icon: "obstruction.png",
              mapIconLow: "genericMapLow.png",
              mapIconMed: "genericMapMed.png",
              mapIconHigh: "genericMapHigh.png"
           },
           type20 : {
              desc: "Operator Actions",
              icon: "operatorAction.png",
              mapIconLow: "genericMapLow.png",
              mapIconMed: "genericMapMed.png",
              mapIconHigh: "genericMapHigh.png"
           },
           type21 : {
              desc: "Car parks",
              icon: "parking.png",
              mapIconLow: "genericMapLow.png",
              mapIconMed: "genericMapMed.png",
              mapIconHigh: "genericMapHigh.png"
           },
           type22 : {
              desc: "Precipitation",
              icon: "precipitation.png",
              mapIconLow: "genericMapLow.png",
              mapIconMed: "genericMapMed.png",
              mapIconHigh: "genericMapHigh.png"
           },
           type23 : {
              desc: "Road conditions",
              icon: "roadCondition.png",
              mapIconLow: "genericMapLow.png",
              mapIconMed: "genericMapMed.png",
              mapIconHigh: "genericMapHigh.png"
           },
           type24 : {
              desc: "Traffic Restrictions",
              icon: "trafficRestriction.png",
              mapIconLow: "genericMapLow.png",
              mapIconMed: "genericMapMed.png",
              mapIconHigh: "genericMapHigh.png"
           },
           type25 : {
              desc: "Road works",
              icon: "operatorAction.png",
              mapIconLow: "operatorActionMapLow.png",
              mapIconMed: "operatorActionMapMed.png",
              mapIconHigh: "operatorActionMapHigh.png"
           },
           type26 : {
              desc: "Rerouting",
              icon: "rerouting.png",
              mapIconLow: "genericMapLow.png",
              mapIconMed: "genericMapMed.png",
              mapIconHigh: "genericMapHigh.png"
           }, 
           type27 : {
              desc: "Skid hazards",
              icon: "slippery.png",
              mapIconLow: "genericMapLow.png",
              mapIconMed: "genericMapMed.png",
              mapIconHigh: "genericMapHigh.png"
           },
           type28 : {
              desc: "Traffic signal plans",
              icon: "operatorAction.png",
              mapIconLow: "genericMapLow.png",
              mapIconMed: "genericMapMed.png",
              mapIconHigh: "genericMapHigh.png"
           },
           type29 : {
              desc: "Snow/Ice Equipment",
              icon: "snowChains.png",
              mapIconLow: "genericMapLow.png",
              mapIconMed: "genericMapMed.png",
              mapIconHigh: "genericMapHigh.png"
           },
           type30 : {
              desc: "Snow on the road(s)",
              icon: "snow.png",
              mapIconLow: "snowMapLow.png",
              mapIconMed: "snowMapMed.png",
              mapIconHigh: "snowMapHigh.png"
           },
           type31 : {
              desc: "Travel time",
              icon: "travelTime.png",
              mapIconLow: "genericMapLow.png",
              mapIconMed: "genericMapMed.png",
              mapIconHigh: "genericMapHigh.png"
           },
           type32 : {
              desc: "Weather data",
              icon: "weatherData.png",
              mapIconLow: "weatherMapLow.png",
              mapIconMed: "weatherMapMed.png",
              mapIconHigh: "weatherMapHigh.png"
           },
           type33 : {
              desc: "Wind",
              icon: "wind.png",
              mapIconLow: "windMapLow.png",
              mapIconMed: "windMapMed.png",
              mapIconHigh: "windMapHigh.png"
           }
        };



var trafficEventSubTypes = {  
   subType1: "abnormal load(s)",
   subType2: "exceptional load warning cleared",
   subType3:"Earlier accident(s)",
   subType4:"accident involving bus(es)",
   subType5:"secondary accident(s)",
   subType6:"chemical spillage accident(s)",
   subType7:"fuel spillage accident(s)",
   subType8:"accident involving heavy lorr(y/ies)",
   subType9:"accident(s)",
   subType10:"accident clearance",
   subType11:"multi-vehicle accident",
   subType12:"serious accident(s)",
   subType13:"accident investigation work",
   subType14:"accident cleared",
   subType15:"accident(s) involving hazardous materials",
   subType16:"air crash",
   subType17:"air raid",
   subType18:"jackknifed articulated lorr(yes)",
   subType19:"jackknifed caravan(s)",
   subType20:"jackknifed trailer(s)",
   subType21:"alarm call important new information on this frequency follows now",
   subType22:"alarm call new information will be broadcast between these times",
   subType23:"all accident cleared, no problems to report",
   subType24:"additional local information is provided by another TMC service",
   subType25:"herd of animals on the road",
   subType26:"large animals on the road",
   subType27:"animals on the road",
   subType28:"oil spillage accident(s)",
   subType29:"overturned heavy lorr(yes)",
   subType30:"overturned vehicle(s)",
   subType31:"all car parks full",
   subType32:"additional public transport information is provided by another TMC service",
   subType33:"danger of aquaplaning",
   subType34:"vehicle(s) spun around",
   subType35:"additional regional information is provided by another TMC service",
   subType36:"avalanches",
   subType37:"average speed",
   subType38:"broken-down vehicle clearance",
   subType39:"broken down bus(es)",
   subType40:"breakdown cleared",
   subType41:"broken down vehicle(s)",
   subType42:"blizzard",
   subType43:"blowing dust",
   subType44:"blowing snow",
   subType45:"bridge blocked",
   subType46:"bridge closed",
   subType47:"burst pipe",
   subType48:"bus services irregular: delays",
   subType49:"bus services not operating",
   subType50:"burst water main",
   subType51:"carpool lane in operation",
   subType52:"cancellations",
   subType53:"message cancelled",
   subType54:"closures due to bad weather",
   subType55:"connecting carriageway blocked",
   subType56:"connecting carriageway closed",
   subType57:"children on roadway",
   subType58:"clearing action",
   subType59:"clearance work",
   subType60:"overnight closures",
   subType61:"emergency telephones not working",
   subType62:"convoy service due to bad weather",
   subType63:"roads permanently closed for the winter",
   subType64:"carpool restrictions changed",
   subType65:"carpool restrictions lifted",
   subType66:"contraflow",
   subType67:"concentration",
   subType68:"contraflow removed",
   subType69:"closed for vehicles with only one occupant",
   subType70:"closed for vehicles with less than three occupants",
   subType71:"convoy cleared",
   subType72:"convoy(s)",
   subType73:"all carriageways cleared",
   subType74:"cyclists on roadway",
   subType75:"difficult driving conditions",
   subType76:"extremely hazardous driving conditions",
   subType77:"air raid warning cancelled",
   subType78:"driving conditions improved",
   subType79:"hazardous driving conditions",
   subType80:"detailed information will be given on audio program broadcast",
   subType81:"delayed until further notice",
   subType82:"delays cleared",
   subType83:"detailed information is provided by another TMC provider",
   subType84:"long delays",
   subType85:"delays",
   subType86:"diversion in operation",
   subType87:"service suspended",
   subType88:"delays of uncertain duration",
   subType89:"very long delays",
   subType90:"delays expected to be cleared",
   subType91:"athletics meeting",
   subType92:"bomb alert",
   subType93:"bull fight",
   subType94:"ball game",
   subType95:"boxing tournament",
   subType96:"give way to emergency vehicles on the carpool lane",
   subType97:"cricket match",
   subType98:"crowd",
   subType99:"cycle race",
   subType100:"fair",
   subType101:"football match",
   subType102:"emergency call facilities restored",
   subType103:"golf tournament",
   subType104:"give way to the emergency vehicles on the heavy vehicle lane",
   subType105:"international sports meeting",
   subType106:"high-speed emergency vehicle(s)",
   subType107:"march",
   subType108:"match",
   subType109:"emergency vehicle(s)",
   subType110:"emergency vehicle warning cleared",
   subType111:"public disturbance",
   subType112:"procession",
   subType113:"earthquake damage",
   subType114:"race meeting",
   subType115:"security alert",
   subType116:"show",
   subType117:"security incident",
   subType118:"show jumping",
   subType119:"several major events",
   subType120:"state occasion",
   subType121:"sports meeting",
   subType122:"sightseers obstructing access",
   subType123:"strike",
   subType124:"sports traffic cleared",
   subType125:"security alert cleared",
   subType126:"traffic has returned to normal",
   subType127:"tournament",
   subType128:"tennis tournament",
   subType129:"evacuation",
   subType130:"ceremonial event",
   subType131:"demonstration",
   subType132:"festival",
   subType133:"major event",
   subType134:"parade",
   subType135:"exhibition",
   subType136:"water sports meeting",
   subType137:"winter sports meeting",
   subType138:"express lanes blocked",
   subType139:"express lanes closed",
   subType140:"severe exhaust pollution",
   subType141:"fog forecast withdrawn",
   subType142:"grass fire",
   subType143:"serious fire",
   subType144:"flooding",
   subType145:"flash floods",
   subType146:"flow",
   subType147:"fallen trees",
   subType148:"dense fog",
   subType149:"freezing fog",
   subType150:"fog",
   subType151:"patchy fog",
   subType152:"fog cleared",
   subType153:"fallen power cables",
   subType154:"heavy frost",
   subType155:"frost",
   subType156:"ferry service not operating",
   subType157:"oil on road",
   subType158:"funfair",
   subType159:"gales",
   subType160:"gas leak",
   subType161:"gas main work",
   subType162:"gritting vehicles in use",
   subType163:"gunfire on roadway",
   subType164:"damaging hail",
   subType165:"hail",
   subType166:"hazardous load warning cleared",
   subType167:"vehicle(s) carrying hazardous materials",
   subType168:"broken down heavy lorr(y/ies)",
   subType169:"temporary height limit lifted",
   subType170:"temporary height limit",
   subType171:"high-speed chase",
   subType172:"hurricane force winds",
   subType173:"information available",
   subType174:"ice build-up",
   subType175:"almost impassable",
   subType176:"impassable",
   subType177:"incident(s)",
   subType178:"individual vehicle data",
   subType179:"carpool lane closed",
   subType180:"one lane blocked",
   subType181:"two lanes blocked",
   subType182:"three lanes blocked",
   subType183:"crawler lane blocked",
   subType184:"bus lane blocked",
   subType185:"centre lane(s) blocked",
   subType186:"slow vehicle lane blocked",
   subType187:"emergency lane blocked",
   subType188:"hard shoulder blocked",
   subType189:"lane(s) blocked",
   subType190:"left lane(s) blocked",
   subType191:"carpool lane blocked",
   subType192:"right lane(s) blocked",
   subType193:"turning lane blocked",
   subType194:"heavy vehicle lane blocked",
   subType195:"lane blockages cleared",
   subType196:"one lane closed",
   subType197:"two lanes closed",
   subType198:"three lanes closed",
   subType199:"crawler lane closed",
   subType200:"bus lane closed",
   subType201:"centre lane(s) closed",
   subType202:"slow vehicle lane closed",
   subType203:"emergency lane closed",
   subType204:"level crossing failure",
   subType205:"hard shoulder closed",
   subType206:"loose chippings",
   subType207:"left lane(s) closed",
   subType208:"overtaking lane(s) closed",
   subType209:"right lane(s) closed",
   subType210:"lane(s) closed",
   subType211:"turning lane closed",
   subType212:"heavy vehicle lane closed",
   subType213:"level crossing now working normally",
   subType214:"local lanes blocked",
   subType215:"local lanes closed",
   subType216:"long load(s)",
   subType217:"temporary length limit lifted",
   subType218:"temporary length limit",
   subType219:"carriageway reduced to one lane",
   subType220:"carriageway reduced to two lanes",
   subType221:"carriageway reduced to three lanes",
   subType222:"left-hand parallel carriageway blocked",
   subType223:"left-hand parallel carriageway closed",
   subType224:"no problems to report",
   subType225:"normal lane regulations restored",
   subType226:"lane closures removed",
   subType227:"lane restrictions lifted",
   subType228:"stationary traffic",
   subType229:"queuing traffic",
   subType230:"slow traffic",
   subType231:"heavy traffic",
   subType232:"traffic flowing freely",
   subType233:"long queues",
   subType234:"low sun glare",
   subType235:"landslips",
   subType236:"traffic problem",
   subType237:"loose sand on road",
   subType238:"traffic heavier than normal",
   subType239:"traffic very much heavier than normal",
   subType240:"overtaking lane(s) blocked",
   subType241:"marathon",
   subType242:"moving hazards on the road",
   subType243:"military convoy(s)",
   subType244:"market",
   subType245:"electronic signs repaired",
   subType246:"mud slide",
   subType247:"motor vehicle restrictions lifted",
   subType248:"next arrival",
   subType249:"normal services resumed",
   subType250:"next departure",
   subType251:"no information available",
   subType252:"narrow lanes",
   subType253:"null message - completely silent",
   subType254:"emergency telephone number not working",
   subType255:"new road layout",
   subType256:"null message with location",
   subType257:"object(s) on roadway something that does not necessarily block the road or part of it}",
   subType258:"occupancy",
   subType259:"obstacle clearance",
   subType260:"overheight vehicle(s)",
   subType261:"overheight warning system triggered",
   subType262:"obstruction(s) on the road",
   subType263:"petrol on roadway",
   subType264:"objects falling from moving vehicle",
   subType265:"open",
   subType266:"obstacle signalling",
   subType267:"obstruction warning withdrawn",
   subType268:"passable with care",
   subType269:"parallel carriageway blocked",
   subType270:"parallel carriageway closed",
   subType271:"people on roadway",
   subType272:"no parking allowed",
   subType273:"only a few spaces available",
   subType274:"no parking information available",
   subType275:"car park full",
   subType276:"park and ride trip time",
   subType277:"no more parking spaces available",
   subType278:"multi story car parks full",
   subType279:"precipitation on the area",
   subType280:"no park and ride information to report",
   subType281:"park and ride information available again",
   subType282:"normal parking restrictions lifted",
   subType283:"park and ride service not operating",
   subType284:"park and ride service operating",
   subType285:"special public transport services operating",
   subType286:"prohibited vehicle(s) on the roadway",
   subType287:"no park and ride information",
   subType288:"enough spaces available",
   subType289:"special parking restrictions lifted",
   subType290:"less than XX parking spaces available",
   subType291:"special parking restrictions in force",
   subType292:"passable",
   subType293:"police directing traffic via the bus lane",
   subType294:"police directing traffic via the carpool lane",
   subType295:"police directing traffic via the heavy vehicle lane",
   subType296:"public transport services not operating",
   subType297:"public transport strike",
   subType298:"rail crash",
   subType299:"rerouting advised",
   subType300:"freezing rain",
   subType301:"heavy rain",
   subType302:"rain",
   subType303:"blocked ahead",
   subType304:"bridge demolition work",
   subType305:"entry blocked",
   subType306:"black ice",
   subType307:"blasting work",
   subType308:"bridge maintenance work",
   subType309:"exit blocked",
   subType310:"road cleared",
   subType311:"closed ahead",
   subType312:"blocked",
   subType313:"road closed",
   subType314:"entry slip road(s) closed",
   subType315:"ramp control signals working incorrectly",
   subType316:"road cleared",
   subType317:"right-hand parallel carriageway closed",
   subType318:"reopened",
   subType319:"no through traffic",
   subType320:"construction work",
   subType321:"road conditions improved",
   subType322:"reckless driver(s)",
   subType323:"entry slip road blocked",
   subType324:"entry slip road closed",
   subType325:"restrictions lifted",
   subType326:"entry reopened",
   subType327:"restrictions",
   subType328:"rescue and recovery work",
   subType329:"slip roads closed",
   subType330:"ice",
   subType331:"road closed intermittently",
   subType332:"tram service not operating",
   subType333:"leaves on road",
   subType334:"road layout unchanged",
   subType335:"mud on road",
   subType336:"maintenance work",
   subType337:"maintenance vehicles merging into traffic flow",
   subType338:"no motor vehicles",
   subType339:"slow moving maintenance vehicle(s)",
   subType340:"road marking work",
   subType341:"slow moving maintenance vehicle warnings withdrawn",
   subType342:"new roadworks layout",
   subType343:"ramp control signals not working",
   subType344:"all carriageways reopened",
   subType345:"rockfalls",
   subType346:"right-hand parallel carriageway blocked",
   subType347:"road surface in poor condition",
   subType348:"intermittent rerouting",
   subType349:"rugby match",
   subType350:"central reservation work",
   subType351:"slip roads blocked",
   subType352:"rail services irregular. Delays",
   subType353:"slippery road",
   subType354:"rail services not operating",
   subType355:"slip roads reopened",
   subType356:"slip road restrictions",
   subType357:"public transport services resumed",
   subType358:"roadworks cleared",
   subType359:"wet and icy roads",
   subType360:"roadworks",
   subType361:"long-term roadworks",
   subType362:"major roadworks",
   subType363:"resurfacing work",
   subType364:"roadwork clearance in progress",
   subType365:"exit slip road blocked",
   subType366:"exit slip road closed",
   subType367:"exit slip road(s) closed",
   subType368:"exit reopened",
   subType369:"service area busy",
   subType370:"salting in progress",
   subType371:"sandstorms",
   subType372:"service area overcrowded, drive to another service area",
   subType373:"single alternate line traffic",
   subType374:"civil emergency",
   subType375:"service withdrawn",
   subType376:"Stato decodifica TMC",
   subType377:"sewer overflow",
   subType378:"civil emergency cancelled",
   subType379:"service(s) fully booked",
   subType380:"service area, fuel station closed",
   subType381:"heavy snowfall",
   subType382:"snowfall",
   subType383:"fuel station reopened",
   subType384:"shed load(s)",
   subType385:"skid hazard reduced",
   subType386:"sleet",
   subType387:"slush",
   subType388:"snow chains mandatory",
   subType389:"closed due to smog alert",
   subType390:"smog alert",
   subType391:"smoke hazard",
   subType392:"spillage occurring from moving vehicle",
   subType393:"smog alert ended",
   subType394:"snowploughs in use",
   subType395:"deep snow",
   subType396:"fresh snow",
   subType397:"packed snow",
   subType398:"snow drifts",
   subType399:"service not operating, substitute service available.",
   subType400:"lane control signs not working",
   subType401:"snow cleared",
   subType402:"police checkpoint",
   subType403:"spillage on the road",
   subType404:"spray hazard",
   subType405:"snow chains recommended",
   subType406:"service area, restaurant closed",
   subType407:"snow on the road",
   subType408:"restaurant reopened",
   subType409:"free shuttle service operating",
   subType410:"severe smog",
   subType411:"shuttle service operating",
   subType412:"storm damage",
   subType413:"stud tyres are not authorised",
   subType414:"terrorist incident",
   subType415:"storm force winds",
   subType416:"stud tyres may be used",
   subType417:"subsidence",
   subType418:"slow vehicle(s)",
   subType419:"swarms of insects",
   subType420:"sewer collapse",
   subType421:"surface water hazard",
   subType422:"lane control signs working incorrectly",
   subType423:"lane control signs operating",
   subType424:"showers",
   subType425:"switch your car radio to XX",
   subType426:"temporary axle load limit",
   subType427:"temporary axle weight limit lifted",
   subType428:"traffic building up",
   subType429:"traffic signal control computer not working",
   subType430:"traffic congestion",
   subType431:"traffic problem cleared",
   subType432:"traffic disruption cleared",
   subType433:"traffic easing",
   subType434:"extreme heat",
   subType435:"temperature falling",
   subType436:"temporary weight limit lifted",
   subType437:"temporary gross weight limit",
   subType438:"thunderstorms",
   subType439:"national traffic information is provided by another TMC service",
   subType440:"only major road information provided by this service",
   subType441:"traffic lights working incorrectly",
   subType442:"traffic lights not working",
   subType443:"temporary traffic lights",
   subType444:"track-laying vehicle(s)",
   subType445:"less extreme temperatures expected",
   subType446:"snow tyres mandatory",
   subType447:"this message is for test purposes only. Please ignore",
   subType448:"current temperature",
   subType449:"normal traffic expected",
   subType450:"temporary traffic lights not working",
   subType451:"tornadoes",
   subType452:"restrictions for high-sided vehicles lifted",
   subType453:"snow tyres recommended",
   subType454:"trade fair",
   subType455:"traffic regulations have been changed",
   subType456:"trip time",
   subType457:"tornado warning ended",
   subType458:"traffic signal timings changed",
   subType459:"traffic signals repaired",
   subType460:"no TMC service available",
   subType461:"through traffic lanes blocked",
   subType462:"through traffic lanes closed",
   subType463:"travel time",
   subType464:"tunnel blocked",
   subType465:"tunnel closed",
   subType466:"tunnel ventilation not working",
   subType467:"temporary traffic lights working incorrectly",
   subType468:"information restricted to this area",
   subType469:"active TMC service on this frequency to be resumed",
   subType470:"extreme cold",
   subType471:"no detailed regional information provided by this service",
   subType472:"only local information provided by this service",
   subType473:"no new traffic information available",
   subType474:"no cross-border information provided by this service",
   subType475:"no public transport information available",
   subType476:"only regional information provided by this service",
   subType477:"TMC broadcast on this frequency will stop",
   subType478:"information is no longer valid",
   subType479:"previous annoucement about this or other TMC services no longer valid",
   subType480:"no detailed local information provided by this service",
   subType481:"reference to audio programmes no longer valid",
   subType482:"reference to other TMC services no longer valid",
   subType483:"use of bus lane allowed under carpool restriction",
   subType484:"use of bus lane allowed for all vehicles",
   subType485:"use of carpool lane allowed for all vehicles",
   subType486:"urgent information will be given on normal program broadcast",
   subType487:"use of hard shoulder allowed",
   subType488:"use of heavy vehicle lane allowed for all vehicles",
   subType489:"underground services irregular",
   subType490:"underground service not operating",
   subType491:"vehicle fire(s)",
   subType492:"visibility reduced",
   subType493:"variable message signs not working",
   subType494:"vehicle with overheight load, danger",
   subType495:"vehicles slowing to look at accident(s)",
   subType496:"dangerous slow moving vehicle in the roadway",
   subType497:"visibility improved",
   subType498:"vehicle(s) on wrong carriageway",
   subType499:"variable message signs working incorrectly",
   subType500:"variable message signs operating",
   subType501:"dangerous vehicle warning cleared",
   subType502:"work on buried cables",
   subType503:"work on buried services",
   subType504:"white out",
   subType505:"crosswinds",
   subType506:"gusty winds",
   subType507:"strong winds",
   subType508:"strong winds have eased",
   subType509:"wide load(s)",
   subType510:"temporary width limit lifted",
   subType511:"temporary width limit",
   subType512:"water main work",
   subType513:"winter equipment recommended",
   subType514:"winter equipment mandatory",
   subType515:"winter storm",
   subType516:"weather situation improved",
   subType517:"weather expected to improve",
   subType518:"wind from left side",
   subType519:"wind from right side"
};
